---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "monitor"
  namespace: "default"
  labels:
    app: "monitor-pod"
spec:
  ports:
  - protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    app: "monitor-pod"
  type: "ClusterIP"
